version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: naidp_dev
      POSTGRES_USER: naidp
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  user-api:
    build:
      context: .
      dockerfile: apps/user-api/Dockerfile.dev
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://naidp:password@postgres:5432/naidp_dev
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=dev-jwt-secret
    volumes:
      - ./apps/user-api:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis
    command: npm run dev

  admin-api:
    build:
      context: .
      dockerfile: apps/admin-api/Dockerfile.dev
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://naidp:password@postgres:5432/naidp_dev
      - ADMIN_API_PORT=3001
    volumes:
      - ./apps/admin-api:/app
      - /app/node_modules
    depends_on:
      - postgres
    command: npm run dev

volumes:
  postgres_dev_data:

networks:
  default:
    name: naidp-dev-network